<?php

namespace App\Http\Controllers;
use App\Model;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
class StkController extends Controller
{
    /**
     * Use this function to initiate an STKPush Simulation
     * @param $BusinessShortCode | The organization shortcode used to receive the transaction.
     * @param $LipaNaMpesaPasskey | The password for encrypting the request. This is generated by base64 encoding BusinessShortcode, Passkey and Timestamp.
     * @param $TransactionType | The transaction type to be used for this request. Only CustomerPayBillOnline is supported.
     * @param $Amount | The amount to be transacted.
     * @param $PartyA | The MSISDN sending the funds.
     * @param $PartyB | The organization shortcode receiving the funds
     * @param $PhoneNumber | The MSISDN sending the funds.
     * @param $CallBackURL | The url to where responses from M-Pesa will be sent to.
     * @param $AccountReference | Used with M-Pesa PayBills.
     * @param $TransactionDesc | A description of the transaction.
     * @param $Remark | Remarks
     * @return mixed|string
     */
    public function STKPushSimulation(){
       $auth_url='https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials';
       $stk_push_url='https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest';
       $consumer_key='D9WURM6T1uxb4NlATqqGKlzCS7GjHfd6';
       $consumer_secret='V926ag4DBX5axh6G';
       $credentials=base64_encode($consumer_key.':'.$consumer_secret);

       $ch=curl_init();
       curl_setopt($ch,CURLOPT_URL,$auth_url);
       curl_setopt($ch,CURLOPT_HTTPHEADER,array('Authorization: Basic '.$credentials));
       curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
       curl_setopt($ch,CURLOPT_HEADER,false);
       curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);

       $curl_response=curl_exec($ch);
       $access_token=json_decode($curl_response)->access_token;

       curl_setopt($ch,CURLOPT_URL,$stk_push_url);
       curl_setopt($ch,CURLOPT_HTTPHEADER,array('Content-Type:application/json','Authorization:Bearer '.$access_token));

       $timestamp=date('YmdHis');
       $passkey='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919';
       $shortCode=174379;
       $password=base64_encode($shortCode.$passkey.$timestamp);

       $curl_post_data=[
           'BusinessShortCode'      =>'174379',
           'Password'               =>$password,
           'Timestamp'              =>$timestamp,
           'TransactionType'        =>'CustomerPayBillOnline',
           'Amount'                 =>'1',
           'PartyA'                 =>'254748730956',
           'PartyB'                 =>'174379',
           'PhoneNumber'            =>'254748730956',
           'CallBackURL'            =>'https://46815095.ngrok.io/api/confirmation',
           'AccountReference'       =>'MillerJuma',
           'TransactionDesc'        =>'Account'    

       ];

       $data_string=json_encode($curl_post_data);
       curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
       curl_setopt($ch,CURLOPT_POST,1);
       curl_setopt($ch,CURLOPT_POSTFIELDS,$data_string);
       curl_setopt($ch,CURLOPT_HEADER,0);

       $curl_res=curl_exec($ch);
       print_r($curl_res);
    }
    public function confirmation(Request $request){

        $callbackData=$request->all();
        $callbackData=json_encode($callbackData);
        $callbackData=json_decode($callbackData);

        $resultCode       =$callbackData->Body->stkCallback->ResultCode;
        $resultDesc       =$callbackData->Body->stkCallback->ResultDesc;
        $merchantRequestID=$callbackData->Body->stkCallback->MerchantRequestID;
        $checkoutRequestID=$callbackData->Body->stkCallback->CheckoutRequestID;

        $amount             =$callbackData->Body->stkCallback->CallbackMetadata->Item[0]->Value;
        $mpesaReceiptNumber =$callbackData->Body->stkCallback->CallbackMetadata->Item[1]->Value;
        $transactionDate    =$callbackData->Body->stkCallback->CallbackMetadata->Item[3]->Value;
        $phoneNumber        =$callbackData->Body->stkCallback->CallbackMetadata->Item[4]->Value;

       
          DB::table('lipa_na_mpesa')->insert([
            'result_code'   =>$resultCode,
            'result_desc'   =>$resultDesc,
            'merchant_request_id'=>$merchantRequestID,
            'checkout_request_id'=>$checkoutRequestID,
            'amount'             =>$amount,
            'mpesa_receipt_number'=>$mpesaReceiptNumber,
            'transaction_date'    =>$transactionDate,
            'phone_number'        =>$phoneNumber
          ]);
          echo json_encode('payment successful');
     
    }
}
